# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool: mylocalPool


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    arguments: '--configuration Debug'
- task: DotNetCoreCLI@2
  displayName: Run test
  inputs:
    command: 'test'
    projects: 'TestRailProject/TestRailProject.csproj'

- task: PublishAllureReport@1
  displayName: Publish Report
  inputs:
    allureVersion: '2.27.0'
    testResultsDir: TestRailProject/bin/Debug/net8.0/allure-results
    reportName: Report

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'